/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasteRouteImport } from './routes/taste'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ForYouRouteImport } from './routes/for-you'
import { Route as CellarRouteImport } from './routes/cellar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WineIdRouteImport } from './routes/wine.$id'
import { Route as CellarOverviewRouteImport } from './routes/cellar.overview'
import { Route as WineIdPairingsRouteImport } from './routes/wine.$id.pairings'
import { Route as WineIdNotesRouteImport } from './routes/wine.$id.notes'

const TasteRoute = TasteRouteImport.update({
  id: '/taste',
  path: '/taste',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ForYouRoute = ForYouRouteImport.update({
  id: '/for-you',
  path: '/for-you',
  getParentRoute: () => rootRouteImport,
} as any)
const CellarRoute = CellarRouteImport.update({
  id: '/cellar',
  path: '/cellar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WineIdRoute = WineIdRouteImport.update({
  id: '/wine/$id',
  path: '/wine/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CellarOverviewRoute = CellarOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => CellarRoute,
} as any)
const WineIdPairingsRoute = WineIdPairingsRouteImport.update({
  id: '/pairings',
  path: '/pairings',
  getParentRoute: () => WineIdRoute,
} as any)
const WineIdNotesRoute = WineIdNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => WineIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cellar': typeof CellarRouteWithChildren
  '/for-you': typeof ForYouRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/taste': typeof TasteRoute
  '/cellar/overview': typeof CellarOverviewRoute
  '/wine/$id': typeof WineIdRouteWithChildren
  '/wine/$id/notes': typeof WineIdNotesRoute
  '/wine/$id/pairings': typeof WineIdPairingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cellar': typeof CellarRouteWithChildren
  '/for-you': typeof ForYouRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/taste': typeof TasteRoute
  '/cellar/overview': typeof CellarOverviewRoute
  '/wine/$id': typeof WineIdRouteWithChildren
  '/wine/$id/notes': typeof WineIdNotesRoute
  '/wine/$id/pairings': typeof WineIdPairingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cellar': typeof CellarRouteWithChildren
  '/for-you': typeof ForYouRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/taste': typeof TasteRoute
  '/cellar/overview': typeof CellarOverviewRoute
  '/wine/$id': typeof WineIdRouteWithChildren
  '/wine/$id/notes': typeof WineIdNotesRoute
  '/wine/$id/pairings': typeof WineIdPairingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cellar'
    | '/for-you'
    | '/history'
    | '/login'
    | '/me'
    | '/scan'
    | '/search'
    | '/taste'
    | '/cellar/overview'
    | '/wine/$id'
    | '/wine/$id/notes'
    | '/wine/$id/pairings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/cellar'
    | '/for-you'
    | '/history'
    | '/login'
    | '/me'
    | '/scan'
    | '/search'
    | '/taste'
    | '/cellar/overview'
    | '/wine/$id'
    | '/wine/$id/notes'
    | '/wine/$id/pairings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cellar'
    | '/for-you'
    | '/history'
    | '/login'
    | '/me'
    | '/scan'
    | '/search'
    | '/taste'
    | '/cellar/overview'
    | '/wine/$id'
    | '/wine/$id/notes'
    | '/wine/$id/pairings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CellarRoute: typeof CellarRouteWithChildren
  ForYouRoute: typeof ForYouRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  ScanRoute: typeof ScanRoute
  SearchRoute: typeof SearchRoute
  TasteRoute: typeof TasteRoute
  WineIdRoute: typeof WineIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/taste': {
      id: '/taste'
      path: '/taste'
      fullPath: '/taste'
      preLoaderRoute: typeof TasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-you': {
      id: '/for-you'
      path: '/for-you'
      fullPath: '/for-you'
      preLoaderRoute: typeof ForYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cellar': {
      id: '/cellar'
      path: '/cellar'
      fullPath: '/cellar'
      preLoaderRoute: typeof CellarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wine/$id': {
      id: '/wine/$id'
      path: '/wine/$id'
      fullPath: '/wine/$id'
      preLoaderRoute: typeof WineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cellar/overview': {
      id: '/cellar/overview'
      path: '/overview'
      fullPath: '/cellar/overview'
      preLoaderRoute: typeof CellarOverviewRouteImport
      parentRoute: typeof CellarRoute
    }
    '/wine/$id/pairings': {
      id: '/wine/$id/pairings'
      path: '/pairings'
      fullPath: '/wine/$id/pairings'
      preLoaderRoute: typeof WineIdPairingsRouteImport
      parentRoute: typeof WineIdRoute
    }
    '/wine/$id/notes': {
      id: '/wine/$id/notes'
      path: '/notes'
      fullPath: '/wine/$id/notes'
      preLoaderRoute: typeof WineIdNotesRouteImport
      parentRoute: typeof WineIdRoute
    }
  }
}

interface CellarRouteChildren {
  CellarOverviewRoute: typeof CellarOverviewRoute
}

const CellarRouteChildren: CellarRouteChildren = {
  CellarOverviewRoute: CellarOverviewRoute,
}

const CellarRouteWithChildren =
  CellarRoute._addFileChildren(CellarRouteChildren)

interface WineIdRouteChildren {
  WineIdNotesRoute: typeof WineIdNotesRoute
  WineIdPairingsRoute: typeof WineIdPairingsRoute
}

const WineIdRouteChildren: WineIdRouteChildren = {
  WineIdNotesRoute: WineIdNotesRoute,
  WineIdPairingsRoute: WineIdPairingsRoute,
}

const WineIdRouteWithChildren =
  WineIdRoute._addFileChildren(WineIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CellarRoute: CellarRouteWithChildren,
  ForYouRoute: ForYouRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  ScanRoute: ScanRoute,
  SearchRoute: SearchRoute,
  TasteRoute: TasteRoute,
  WineIdRoute: WineIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
