ALTER TABLE public.wines
  ADD COLUMN IF NOT EXISTS purchase_price NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS purchase_currency TEXT DEFAULT 'SEK',
  ADD COLUMN IF NOT EXISTS purchased_at DATE,
  ADD COLUMN IF NOT EXISTS consumed_at DATE,
  ADD COLUMN IF NOT EXISTS quantity INTEGER NOT NULL DEFAULT 1;